# Generated by Django 5.1.7 on 2025-04-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='username',
            new_name='user',
        ),
    ]
