# Generated by Django 5.1.7 on 2025-04-23 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_login_rename_username_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
